global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - 'alert.rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: 'koa_template_app'
    static_configs:
      - targets: ['host.docker.internal:7547'] # 本地应用地址
    scrape_interval: 10s
    metrics_path: '/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node.js应用指标
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['host.docker.internal:9100'] # 如果你运行node_exporter

  # 系统指标（可选）
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['host.docker.internal:8080'] # 容器指标
